# Generated by Django 3.0.3 on 2020-08-27 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('pat_name', models.CharField(max_length=100)),
                ('doc_name', models.CharField(max_length=100)),
                ('pat_email', models.CharField(max_length=100)),
                ('doc_email', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=100)),
                ('meeting_link', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=25)),
                ('timing', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('user_type', models.CharField(default='doctor', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('user_type', models.CharField(default='user', max_length=10)),
            ],
        ),
    ]
