# Generated by Django 3.0.3 on 2020-09-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karm', '0006_auto_20200828_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='visible',
            field=models.CharField(default='False', max_length=10),
        ),
    ]
